//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCupOverflows
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyCupOverflowsDbEntities : DbContext
    {
        public MyCupOverflowsDbEntities()
            : base("name=MyCupOverflowsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Table> Admin_Table { get; set; }
        public virtual DbSet<Branch_Table> Branch_Table { get; set; }
        public virtual DbSet<Orders_Table> Orders_Table { get; set; }
        public virtual DbSet<PaymentModel_Table> PaymentModel_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<Seat_Table> Seat_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
