//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCupOverflows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Table
    {
        public int Id { get; set; }
        public string InOut { get; set; }
        public Nullable<System.DateTime> DateReservation { get; set; }
        public Nullable<int> Seat { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
