//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCupOverflows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Specification { get; set; }
        public Nullable<bool> RestrictedAge { get; set; }
    }
}
